baseurl = "https://miafallon.dev"
title = "home"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
author = "mia fallon"
info = "senior software engineer"
description = "My portfolio, blog, and personal website all-in-one"
keywords = "blog,developer,personal,portfolio"
avatarurl = "images/avatar.jpg"

faviconSVG = "/favicon.svg"

since = 2017

enableTwemoji = true

colorScheme = "dark"
hidecolorschemetoggle = true

# customCSS = ["css/custom.css"]
customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]
[markup.goldmark.renderer]
unsafe = true

[params.goatCounter]
code = "mfallondev"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
authors = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/inform880/"
target = "_blank"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://linkedin.com/in/mia-fallon"
target = "_blank"
[[params.social]]
name = "Discord"
icon = "fa-brands fa-discord fa-2x"
weight = 2
url = "https://discordapp.com/users/178255008788250624"
target = "_blank"
[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 3
url = "/index.xml"
rel = "alternate"
type = "application/rss+xml"
target = "_blank"
[[params.social]]
name = "email"
icon = "fa-solid fa-paper-plane fa-2x"
weight = 4
url = "mailto:mfallondev@gmail.com"
rel = "me"
type = "application/email"

[[menu.main]]
name = "posts"
weight = 1
url = "posts/"
[[menu.main]]
name = "projects"
weight = 2
url = "projects/"


[params.giscus]
repo = "inform880/miafallon.dev"
repoID = "R_kgDOLsPyyA"
category = "General"
categoryID = "DIC_kwDOLsPyyM4CkRjE"
mapping = "title"
strict = "1"
reactionsEnabled = "0"
emitMetadata = "1"
inputPosition = "bottom"
lang = "en"
loading = "lazy"
